authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path(
        'recipes/category/<int:category_id>/',
        views.category,
        name='category'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=65, unique=True)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_is_html = models.BooleanField(default=False)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
            upload_to='recipes/covers/%Y/%m/%d/',
            blank=True,
            default='',
        )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True,
        blank=True,
        default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

recipes/views.py
import os
from .models import Recipe
from django.db.models import Q
# from django.contrib import messages
from django.http.response import Http404
from utils.pagination import make_pagination
from django.shortcuts import (
    render,
    get_list_or_404,
    get_object_or_404,
)

PER_PAGE = int(os.environ.get('PER_PAGE', 9))


def home(request):
    recipes = Recipe.objects.filter(
            is_published=True
        ).order_by('-id')
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)  # noqa 501
    return render(request, "recipes/pages/home.html", context={
            'recipes': page_object,
            'pagination_range': pagination_range,
        })


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by('id')
    )
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)  # noqa 501
    return render(request, "recipes/pages/category.html", context={
        'recipes': page_object,
        'pagination_range': pagination_range,
        'title': f'{recipes[0].category.name} - Category | ',
    })


def recipe(request, id):
    recipe = get_object_or_404(
        Recipe,
        id=id,
        is_published=True,
    )
    return render(request, "recipes/pages/recipe-view.html", context={
        'recipe': recipe,
        'is_detail_page': True,
    })


def search(request):
    search_term = request.GET.get('q', '').strip()
    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term)
            |
            Q(description__icontains=search_term)
        ),
        is_published=True,
    ).order_by('-id')

    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)  # noqa 501

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'Search for "{search_term}" |',
        'search_term': search_term,
        'recipes': page_object,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}',
    })

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/fontawesome.min.css"
  integrity="sha512-cHxvm20nkjOUySu7jdwiUxgGy11vuVPE9YeK89geLMLMMEOcKFyS2i+8wo0FOwyQO/bL8Bvq1KMsqK4bbOsPnA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/brands.min.css"
  integrity="sha512-L+sMmtHht2t5phORf0xXFdTC0rSlML1XcraLTrABli/0MMMylsJi3XA23ReVQkZ7jLkOEIMicWGItyK4CAt2Xw=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/solid.min.css"
  integrity="sha512-bdTSJB23zykBjGDvyuZUrLhHD0Rfre0jxTd0/jpTbV7sZL8DCth/88aHX0bq2RV8HK3zx5Qj6r2rRU/Otsjk+g=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
  {% if recipe.cover.url is not Null %}
    <div class="recipe-cover">
      <a href="{% url 'recipes:recipe' recipe.id %}">
        <img src="{{ recipe.cover.url }}" alt="Temporário">
      </a>
    </div>
  {% endif %}
  <div class="recipe-title-container">
    <h2 class="recipe-title">
      <a href="{% url 'recipes:recipe' recipe.id %}">
        {{ recipe.title }}
      </a>
    </h2>
  </div>
  <div class="recipe-author">
    <span class="recipe-author-item">
      <i class="fas fa-user"></i>
      {% if recipe.author is not None %}
        {% if recipe.author.first_name %}
          {{ recipe.author.first_name }} {{ recipe.author.last_name }}
        {% else %}
          {{ recipe.author.username }}
        {% endif %}
      {% else %}
        Desconhecido
      {% endif %}
    </span>
    <span class="recipe-author-item">
      <i class="fas fa-calendar-alt"></i>
      {{ recipe.created_at|date:'d/m/Y' }} às {{ recipe.created_at|date:'H:i' }}
    </span>
    {% if recipe.category is not None %}
      <span class="recipe-author-item">
        <a href="{% url 'recipes:category' recipe.category.id %}">
          <i class="fas fa-layer-group"></i>
          <span>{{ recipe.category.name }}</span>
        </a>
      </span>
    {% endif %}
  </div>
  <div class="recipe-content">
    <p>{{ recipe.description }}</p>
  </div>
  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-preparation">
      <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
      <div class="recipe-meta-text">
        {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
      </div>
    </div>
    <div class="recipe-meta recipe-servings">
      <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
      <div class="recipe-meta-text">
        {{ recipe.servings }} {{ recipe.servings_unit }}
      </div>
    </div>
  </div>
  {% if is_detail_page is not True %}
    <footer class="recipe-footer">
      <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
        <i class="fas fa-eye"></i>
        <span>Ver mais...</span>
      </a>
    </footer>
  {% endif %}

  {% if is_detail_page is True %}
    <div class="preparation-steps">
      {% if recipe.preparation_is_html is True %}
        {{ recipe.preparation_steps|safe }}
      {% else %}
        {{ recipe.preparation_steps|linebreaksbr }}
      {% endif %}
    </div>
  {% endif %}
</div>